backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

local_backend: true

publish_mode: editorial_workflow # Allows you to save drafts before publishing them
public_folder: /uploads # The src attribute for uploaded media will begin with /images/uploads
media_folder: static/uploads # Media files will be stored in the repo under static/images/uploads
media_library:
  name: cloudinary
  config:
    cloud_name: threesam
    api_key: 464612811924947

collections:
# contributors
  - name: "contributor"
    label: "Contributor"
    folder: 'static/contributors'
    create: true
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - label: "Image"
        name: "image"
        widget: "object"
        fields:
        - label: "Thumbnail"
          name: "thumbnail"
          widget: "image"
          default: ""
          media_library:
            config:
              multiple: true
        - { label: "Alt", name: "alt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "resume"
        name: "Resume"
        widget: "file"
        default: ""
        media_library:
          config:
            multiple: false
# posts
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Blog Post" # Used in the UI
    folder: "static/posts" # The path to the folder where our blog posts are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - label: "Date"
        name: "date"
        widget: "datetime"
        default: ""
        date_format: "DD.MM.YYYY" # e.g. 24.12.2021
        time_format: "HH:mm" # e.g. 21:07
        format: "LLL"
        picker_utc: false
      - label: "Featured Image"
        required: false
        name: "thumbnail"
        widget: "image"
        default: ""
        media_library:
          config:
            multiple: false
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Contributor Reference"
        name: "contributorReference"
        widget: "relation"
        collection: "contributor"
        search_fields: ["title"]
        value_field: "title"
        display_fields: ["title"]
      - label: "Tag"
        name: "tag"
        widget: "relation"
        collection: "tags"
        search_fields: ["title"]
        value_field: "title"
        display_fields: ["thumbnail", "title"]
# projects
  - name: "project"
    label: "Project"
    folder: "static/projects"
    create: true
    fields:
      - { label: "Slug", name: "slug", widget: "string"}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        default: ""
        media_library:
          config:
            multiple: false
      - label: "Contributor Reference"
        name: "contributorReference"
        widget: "relation"
        collection: "contributor"
        search_fields: ["name"]
        value_field: "name"
        display_fields: ["image.thumbnail", "name"]
      - label: "Tag"
        name: "tag"
        widget: "relation"
        collection: "tags"
        search_fields: ["title"]
        value_field: "title"
        display_fields: ["thumbnail", "title"]
# tags
  - name: "tags"
    label: "Tags"
    folder: "static/tags"
    create: true
    fields:
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        default: ""
        media_library:
          config:
            multiple: false